# Simple workflow for putting runner logs in PR comments
name: Comment Runner Log
run-name: Comment Runner Log

on:
  # Allows you to run this workflow manually from the Actions tab AND from other actions (fwTaskPushCreateCheck)
  workflow_dispatch:
    inputs:
      run_id:
        description: Run ID
        required: true
      repo_name:
        description: Repository Name
        required: true
      branch_name:
        description: Branch Name
        required: true
      

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pull-requests: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "commentLog"
  cancel-in-progress: true

jobs:
  comment:
    env:
      ACTIONS_RUNNER_DEBUG: true 
      GH_TOKEN: ${{ github.token }}
    runs-on: self-hosted
    steps:
      # Set Output
      
      # - name: Get Output
      #   id: log
      #   run: |
      #     echo "LOG=$( gh run view ${{ inputs.run_id }} --log ) >> $env:GITHUB_OUTPUT
      # - name: Debug Log
      #   run: |
      #     echo ${{ steps.log.outputs.LOG || 'none'}}
      # - name: Comment Pull Request With Log
      #   run: |
      #     gh pr comment --body "${{ toJSON(steps.log.outputs.LOG || 'none' ) }}"
      - name: Log To File
        run: |
          gh run view ${{ inputs.run_id }} --log > output.log
      - name: Remove control characters
        run: |
          Get-Content output.log -Encoding UTF8 | Set-Content outputUTF8.log
      - name: Comment Pull Request With Log
        run: |
          gh pr comment -R ${{ inputs.repo_name }} ${{ inputs.branch_name }} --body-file outputUTF8.log
      


      