# Simple workflow for debugging github actions
name: DEBUG
run-name: DEBUG

on:
  # Allows you to run this workflow manually from the Actions tab AND from other actions (fwTaskPushCreateCheck)
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pull-requests: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "debug"
  cancel-in-progress: true

jobs:
  job1:
    env:
      ACTIONS_RUNNER_DEBUG: true 
      GH_TOKEN: ${{ github.token }}
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment Pull Request Pre Deploy
        run: |
          gh pr comment --body "DEBUG START"

      # Test output
      - name: Echo Commands
        id: echo
        run: |
          echo "Test" > output.txt
          echo "TEST=test" >> $env:GITHUB_OUTPUT
      
      - name: Work with output
        run: |
          echo "test=${{ steps.echo.outputs.TEST }}""
          gh pr comment --body "DEBUG END"